#!/usr/bin/env bash -eu

_some() {
  if [[ -z "$@" ]]; then
    echo "Please tell me some path"
    return
  fi
  
  echo "command ? ___ $@"
  
  read command
  
  if [[ ! $(which $command) ]]; then
    echo "$command command not found"
    return
  fi
  
  eval "$command $@"
}

_some $@

