#!/usr/bin/env bash -eu

# $ docker-rmi
#
# List docker images and remove it
#
# Usage
# 
# $ docker-rmi
# 
# $ docker-rmi -f
#   ( Use `$ docker rmi` option )
#

readonly image_list=$(docker images | tail -n +2)
readonly selected_line=$(echo "$image_list" | peco)

readonly selected_image_name=$(echo "$selected_line" | awk '{ print $1 }')
readonly selected_image_id=$(echo "$selected_line" | awk '{ print $3 }')

if [[ -z "$selected_image_id" ]]; then
  echo Image not selected
  exit
fi

echo "$selected_image_name : $selected_image_id" selected
docker rmi "$selected_image_id" "$@"; readonly docker_rmi_exit_code="$?"

