#!/usr/bin/env zsh -eu

# !BROKEN!
# This widget can up-history only recent two histories
if [ ! $(which zsh) ]; then echo "You need zsh" && exit; fi

up_refreshed_history() {
  fc -R
  zle up-history
}

zle -N up-refreshed-history up_refreshed_history

# Recipi
# bindkey '^[[A' # up arrow key
