#!/usr/bin/env bash -eu

# Usage
#
# $ command 
#
# $ command HEAD~3
#
# EDITOR=vim $ command 
#

readonly editor=${EDITOR:-vim}

selected_file=$(git-recent-peco $@)

if [[ -z "$selected_file" ]]; then
  echo "No file selected"
  exit 1
else
  eval "$EDITOR" "$selected_file"
fi

